# Generated by Django 3.0.8 on 2020-07-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_death', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('username', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('difficulty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_victim', to='api.Victim')),
                ('pre_victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_victim', to='api.Victim')),
            ],
        ),
    ]
