# Generated by Django 3.0.8 on 2020-07-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
